# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTextSwitch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTextSwitch

  pod 'RCRunkeeperSwitch', :git => 'https://github.com/rcgary/RCRunkeeperSwitch.git'

end
